Merge copyright.check.mk with utils.mk: avoids tightened build-dependency on cdbs.

diff --git a/1/rules/utils.mk.in b/1/rules/utils.mk.in
--- a/1/rules/utils.mk.in
+++ b/1/rules/utils.mk.in
@@ -1,5 +1,6 @@
 # -*- mode: makefile; coding: utf-8 -*-
 # Copyright © 2003 Colin Walters <walters@debian.org>
+# Copyright © 2005-2010 Jonas Smedegaard <dr@jones.dk>
 # Description: Defines various random rules, including a list-missing rule
 #
 # This program is free software; you can redistribute it and/or
@@ -22,6 +23,23 @@ _cdbs_rules_utils = 1
 
 include $(_cdbs_rules_path)/buildcore.mk$(_cdbs_makefile_suffix)
 
+# Routines convenient for maintainers but unsuitable for build daemons
+#  * strict checking makes rule fail if changed/new hints are found
+ifneq (,$(DEB_MAINTAINER_MODE))
+  DEB_COPYRIGHT_CHECK_STRICT = yes
+endif
+
+# Single regular expression for files to include or ignore
+DEB_COPYRIGHT_CHECK_REGEX ?= .*
+DEB_COPYRIGHT_CHECK_IGNORE_REGEX ?= ^\./debian/(changelog|copyright(|_hints|_newhints))$
+
+# number of lines from the top of each file to investigate
+DEB_COPYRIGHT_CHECK_PARSELINES ?= 99999
+
+DEB_COPYRIGHT_CHECK_SCRIPT ?= licensecheck
+DEB_COPYRIGHT_CHECK_ARGS ?= -c '$(DEB_COPYRIGHT_CHECK_REGEX)' -r --copyright -i '$(DEB_COPYRIGHT_CHECK_IGNORE_REGEX)' -l '$(DEB_COPYRIGHT_CHECK_PARSELINES)' ./*
+DEB_COPYRIGHT_CHECK_INVOKE ?= $(DEB_COPYRIGHT_CHECK_SCRIPT) $(DEB_COPYRIGHT_CHECK_ARGS)
+
 DEB_PHONY_RULES += list-missing
 
 list-missing:
@@ -37,7 +55,53 @@ list-missing:
 	  echo "All files were installed into debian/$(DEB_SOURCE_PACKAGE)."; \
 	fi
 
+pre-build:: debian/stamp-copyright-check
+debian/stamp-copyright-check:
+	@set -e; if [ ! -f debian/copyright_hints ]; then \
+		echo; \
+		echo '$(if $(DEB_COPYRIGHT_CHECK_STRICT),ERROR,WARNING): copyright-check disabled - touch debian/copyright_hints to enable.'; \
+		echo; \
+		$(if $(DEB_COPYRIGHT_CHECK_STRICT),exit 1,:); \
+	elif [ licensecheck = $(DEB_COPYRIGHT_CHECK_SCRIPT) ] && ! which licensecheck > /dev/null; then \
+		echo; \
+		echo '$(if $(DEB_COPYRIGHT_CHECK_STRICT),ERROR,WARNING): copyright-check disabled - licensecheck (from devscripts package) is missing.'; \
+		echo; \
+		$(if $(DEB_COPYRIGHT_CHECK_STRICT),exit 1,:); \
+	elif [ licensecheck = $(DEB_COPYRIGHT_CHECK_SCRIPT) ] && licensecheck --help | grep -qv -- --copyright; then \
+		echo; \
+		echo '$(if $(DEB_COPYRIGHT_CHECK_STRICT),ERROR,WARNING): copyright-check disabled - licensecheck (from devscripts package) seems older than needed 2.10.7.'; \
+		echo; \
+		$(if $(DEB_COPYRIGHT_CHECK_STRICT),exit 1,:); \
+	else \
+		echo; \
+		echo 'Scanning upstream source for new/changed copyright notices...'; \
+		echo; \
+		echo "$(DEB_COPYRIGHT_CHECK_INVOKE) | $(_cdbs_scripts_path)/licensecheck2dep5 > debian/copyright_newhints"; \
+		export LC_ALL=C; \
+		$(DEB_COPYRIGHT_CHECK_INVOKE) | $(_cdbs_scripts_path)/licensecheck2dep5 > debian/copyright_newhints; \
+		echo "`grep -c ^Files: debian/copyright_hints` combinations of copyright and licensing found."; \
+		newstrings=`diff -a -u debian/copyright_hints debian/copyright_newhints | sed '1,2d' | egrep -a '^\+' - | sed 's/^\+//'`; \
+		if [ -n "$$newstrings" ]; then \
+			echo "$(if $(DEB_COPYRIGHT_CHECK_STRICT),ERROR,WARNING): The following (and possibly more) new or changed notices discovered:"; \
+			echo; \
+			echo "$$newstrings" \
+				| perl -ne '/^.{0,60}$$/ or s/^(.{0,60})\b.*$$/$$1…/;s/[^[:print:][:space:]…]//g;$$_ ne $$prev and (($$prev) = $$_) and print' \
+				| sort -m \
+				| head -n 200; \
+			echo; \
+			echo "To fix the situation please do the following:"; \
+			echo "  1) Fully compare debian/copyright_hints with debian/copyright_newhints"; \
+			echo "  2) Update debian/copyright as needed"; \
+			echo "  3) Replace debian/copyright_hints with debian/copyright_newhints"; \
+			$(if $(DEB_COPYRIGHT_CHECK_STRICT),exit 1,:); \
+		else \
+			echo 'No new copyright notices found - assuming no news is good news...'; \
+		fi; \
+		rm -f debian/copyright_newhints; \
+	fi
+	touch $@
+
 clean::
-	rm -f debian/cdbs-install-list debian/cdbs-package-list
+	rm -f debian/cdbs-install-list debian/cdbs-package-list debian/stamp-copyright-check
 
 endif
