Merge build-info.mk rule with utils.mk, and gracefully handle missing binary instead of tightened build-dependency.

diff --git a/1/rules/utils.mk.in b/1/rules/utils.mk.in
--- a/1/rules/utils.mk.in
+++ b/1/rules/utils.mk.in
@@ -40,6 +40,8 @@ DEB_COPYRIGHT_CHECK_SCRIPT ?= licensecheck
 DEB_COPYRIGHT_CHECK_ARGS ?= -c '$(DEB_COPYRIGHT_CHECK_REGEX)' -r --copyright -i '$(DEB_COPYRIGHT_CHECK_IGNORE_REGEX)' -l '$(DEB_COPYRIGHT_CHECK_PARSELINES)' ./*
 DEB_COPYRIGHT_CHECK_INVOKE ?= $(DEB_COPYRIGHT_CHECK_SCRIPT) $(DEB_COPYRIGHT_CHECK_ARGS)
 
+DEB_BUILDINFO_SCRIPT = dh_buildinfo
+
 DEB_PHONY_RULES += list-missing
 
 list-missing:
@@ -101,7 +103,20 @@ debian/stamp-copyright-check:
 	fi
 	touch $@
 
+common-install-arch common-install-indep:: debian/stamp-buildinfo
+debian/stamp-buildinfo:
+	@set -e; if [ dh_buildinfo = $(DEB_BUILDINFO_SCRIPT) ] && ! which dh_buildinfo > /dev/null; then \
+		echo; \
+		echo '$(if $(DEB_BUILDINFO_STRICT),ERROR,WARNING): buildinfo disabled - dh_buildinfo (from dh-buildinfo package) is missing.'; \
+		echo; \
+		$(if $(DEB_BUILDINFO_STRICT),exit 1,:); \
+	else \
+		echo $(DEB_BUILDINFO_SCRIPT);
+		$(DEB_BUILDINFO_SCRIPT);
+	fi
+	touch $@
+
 clean::
-	rm -f debian/cdbs-install-list debian/cdbs-package-list debian/stamp-copyright-check
+	rm -f debian/cdbs-install-list debian/cdbs-package-list debian/stamp-copyright-check debian/stamp-buildinfo
 
 endif
